# Pandas

In [1]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

In [5]:
data_url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data'
df_data = pd.read_csv(data_url,sep="\s+")


In [51]:
df_data.head()

0.00632  18.00  2.310  0  0.5380  6.5750  65.20  4.0900  1  296.0  15.30  \
0  0.02731    0.0   7.07  0   0.469   6.421   78.9  4.9671  2  242.0   17.8   
1  0.02729    0.0   7.07  0   0.469   7.185   61.1  4.9671  2  242.0   17.8   
2  0.03237    0.0   2.18  0   0.458   6.998   45.8  6.0622  3  222.0   18.7   
3  0.06905    0.0   2.18  0   0.458   7.147   54.2  6.0622  3  222.0   18.7   
4  0.02985    0.0   2.18  0   0.458   6.430   58.7  6.0622  3  222.0   18.7   

   396.90  4.98  24.00  
0  396.90  9.14   21.6  
1  392.83  4.03   34.7  
2  394.63  2.94   33.4  
3  396.90  5.33   36.2  
4  394.12  5.21   28.7

In [52]:
df_data.columns = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n']
df_data.head()

a    b     c  d      e      f     g       h  i      j     k       l  \
0  0.02731  0.0  7.07  0  0.469  6.421  78.9  4.9671  2  242.0  17.8  396.90   
1  0.02729  0.0  7.07  0  0.469  7.185  61.1  4.9671  2  242.0  17.8  392.83   
2  0.03237  0.0  2.18  0  0.458  6.998  45.8  6.0622  3  222.0  18.7  394.63   
3  0.06905  0.0  2.18  0  0.458  7.147  54.2  6.0622  3  222.0  18.7  396.90   
4  0.02985  0.0  2.18  0  0.458  6.430  58.7  6.0622  3  222.0  18.7  394.12   

      m     n  
0  9.14  21.6  
1  4.03  34.7  
2  2.94  33.4  
3  5.33  36.2  
4  5.21  28.7

In [57]:
weight = np.array([[1],[2],[3]])
x = np.array([[4],[5],[6]])

In [58]:
print(weight.T)
weightT = weight.T.dot(x)

[[1 2 3]]


In [59]:
print(weightT)

[[32]]


In [61]:
df_data['weight_0'] = 1

In [62]:
df_data

a     b      c  d      e      f      g       h   i      j     k  \
0     0.02731   0.0   7.07  0  0.469  6.421   78.9  4.9671   2  242.0  17.8   
1     0.02729   0.0   7.07  0  0.469  7.185   61.1  4.9671   2  242.0  17.8   
2     0.03237   0.0   2.18  0  0.458  6.998   45.8  6.0622   3  222.0  18.7   
3     0.06905   0.0   2.18  0  0.458  7.147   54.2  6.0622   3  222.0  18.7   
4     0.02985   0.0   2.18  0  0.458  6.430   58.7  6.0622   3  222.0  18.7   
5     0.08829  12.5   7.87  0  0.524  6.012   66.6  5.5605   5  311.0  15.2   
6     0.14455  12.5   7.87  0  0.524  6.172   96.1  5.9505   5  311.0  15.2   
7     0.21124  12.5   7.87  0  0.524  5.631  100.0  6.0821   5  311.0  15.2   
8     0.17004  12.5   7.87  0  0.524  6.004   85.9  6.5921   5  311.0  15.2   
9     0.22489  12.5   7.87  0  0.524  6.377   94.3  6.3467   5  311.0  15.2   
10    0.11747  12.5   7.87  0  0.524  6.009   82.9  6.2267   5  311.0  15.2   
11    0.09378  12.5   7.87  0  0.524  5.889   39.0  5.4509   5  311.0  15.2   
12    0.62976   0.0   8.14  0  0.538  5.949   61.8  4.7075   4  307.0  21.0   
13    0.63796   0.0   8.14  0  0.538  6.096   84.5  4.4619   4  307.0  21.0   
14    0.62739   0.0   8.14  0  0.538  5.834   56.5  4.4986   4  307.0  21.0   
15    1.05393   0.0   8.14  0  0.538  5.935   29.3  4.4986   4  307.0  21.0   
16    0.78420   0.0   8.14  0  0.538  5.990   81.7  4.2579   4  307.0  21.0   
17    0.80271   0.0   8.14  0  0.538  5.456   36.6  3.7965   4  307.0  21.0   
18    0.72580   0.0   8.14  0  0.538  5.727   69.5  3.7965   4  307.0  21.0   
19    1.25179   0.0   8.14  0  0.538  5.570   98.1  3.7979   4  307.0  21.0   
20    0.85204   0.0   8.14  0  0.538  5.965   89.2  4.0123   4  307.0  21.0   
21    1.23247   0.0   8.14  0  0.538  6.142   91.7  3.9769   4  307.0  21.0   
22    0.98843   0.0   8.14  0  0.538  5.813  100.0  4.0952   4  307.0  21.0   
23    0.75026   0.0   8.14  0  0.538  5.924   94.1  4.3996   4  307.0  21.0   
24    0.84054   0.0   8.14  0  0.538  5.599   85.7  4.4546   4  307.0  21.0   
25    0.67191   0.0   8.14  0  0.538  5.813   90.3  4.6820   4  307.0  21.0   
26    0.95577   0.0   8.14  0  0.538  6.047   88.8  4.4534   4  307.0  21.0   
27    0.77299   0.0   8.14  0  0.538  6.495   94.4  4.4547   4  307.0  21.0   
28    1.00245   0.0   8.14  0  0.538  6.674   87.3  4.2390   4  307.0  21.0   
29    1.13081   0.0   8.14  0  0.538  5.713   94.1  4.2330   4  307.0  21.0   
..        ...   ...    ... ..    ...    ...    ...     ...  ..    ...   ...   
475   4.87141   0.0  18.10  0  0.614  6.484   93.6  2.3053  24  666.0  20.2   
476  15.02340   0.0  18.10  0  0.614  5.304   97.3  2.1007  24  666.0  20.2   
477  10.23300   0.0  18.10  0  0.614  6.185   96.7  2.1705  24  666.0  20.2   
478  14.33370   0.0  18.10  0  0.614  6.229   88.0  1.9512  24  666.0  20.2   
479   5.82401   0.0  18.10  0  0.532  6.242   64.7  3.4242  24  666.0  20.2   
480   5.70818   0.0  18.10  0  0.532  6.750   74.9  3.3317  24  666.0  20.2   
481   5.73116   0.0  18.10  0  0.532  7.061   77.0  3.4106  24  666.0  20.2   
482   2.81838   0.0  18.10  0  0.532  5.762   40.3  4.0983  24  666.0  20.2   
483   2.37857   0.0  18.10  0  0.583  5.871   41.9  3.7240  24  666.0  20.2   
484   3.67367   0.0  18.10  0  0.583  6.312   51.9  3.9917  24  666.0  20.2   
485   5.69175   0.0  18.10  0  0.583  6.114   79.8  3.5459  24  666.0  20.2   
486   4.83567   0.0  18.10  0  0.583  5.905   53.2  3.1523  24  666.0  20.2   
487   0.15086   0.0  27.74  0  0.609  5.454   92.7  1.8209   4  711.0  20.1   
488   0.18337   0.0  27.74  0  0.609  5.414   98.3  1.7554   4  711.0  20.1   
489   0.20746   0.0  27.74  0  0.609  5.093   98.0  1.8226   4  711.0  20.1   
490   0.10574   0.0  27.74  0  0.609  5.983   98.8  1.8681   4  711.0  20.1   
491   0.11132   0.0  27.74  0  0.609  5.983   83.5  2.1099   4  711.0  20.1   
492   0.17331   0.0   9.69  0  0.585  5.707   54.0  2.3817   6  391.0  19.2   
493   0.27957   0.0   9.69  0  0.585  5.926   42.6  2.3817   6

In [65]:
df_data = df_data.drop('n',axis=1)
df_data.head()

KeyError: "['n'] not found in axis"

In [64]:
df_data

a     b      c  d      e      f      g       h   i      j     k  \
0     0.02731   0.0   7.07  0  0.469  6.421   78.9  4.9671   2  242.0  17.8   
1     0.02729   0.0   7.07  0  0.469  7.185   61.1  4.9671   2  242.0  17.8   
2     0.03237   0.0   2.18  0  0.458  6.998   45.8  6.0622   3  222.0  18.7   
3     0.06905   0.0   2.18  0  0.458  7.147   54.2  6.0622   3  222.0  18.7   
4     0.02985   0.0   2.18  0  0.458  6.430   58.7  6.0622   3  222.0  18.7   
5     0.08829  12.5   7.87  0  0.524  6.012   66.6  5.5605   5  311.0  15.2   
6     0.14455  12.5   7.87  0  0.524  6.172   96.1  5.9505   5  311.0  15.2   
7     0.21124  12.5   7.87  0  0.524  5.631  100.0  6.0821   5  311.0  15.2   
8     0.17004  12.5   7.87  0  0.524  6.004   85.9  6.5921   5  311.0  15.2   
9     0.22489  12.5   7.87  0  0.524  6.377   94.3  6.3467   5  311.0  15.2   
10    0.11747  12.5   7.87  0  0.524  6.009   82.9  6.2267   5  311.0  15.2   
11    0.09378  12.5   7.87  0  0.524  5.889   39.0  5.4509   5  311.0  15.2   
12    0.62976   0.0   8.14  0  0.538  5.949   61.8  4.7075   4  307.0  21.0   
13    0.63796   0.0   8.14  0  0.538  6.096   84.5  4.4619   4  307.0  21.0   
14    0.62739   0.0   8.14  0  0.538  5.834   56.5  4.4986   4  307.0  21.0   
15    1.05393   0.0   8.14  0  0.538  5.935   29.3  4.4986   4  307.0  21.0   
16    0.78420   0.0   8.14  0  0.538  5.990   81.7  4.2579   4  307.0  21.0   
17    0.80271   0.0   8.14  0  0.538  5.456   36.6  3.7965   4  307.0  21.0   
18    0.72580   0.0   8.14  0  0.538  5.727   69.5  3.7965   4  307.0  21.0   
19    1.25179   0.0   8.14  0  0.538  5.570   98.1  3.7979   4  307.0  21.0   
20    0.85204   0.0   8.14  0  0.538  5.965   89.2  4.0123   4  307.0  21.0   
21    1.23247   0.0   8.14  0  0.538  6.142   91.7  3.9769   4  307.0  21.0   
22    0.98843   0.0   8.14  0  0.538  5.813  100.0  4.0952   4  307.0  21.0   
23    0.75026   0.0   8.14  0  0.538  5.924   94.1  4.3996   4  307.0  21.0   
24    0.84054   0.0   8.14  0  0.538  5.599   85.7  4.4546   4  307.0  21.0   
25    0.67191   0.0   8.14  0  0.538  5.813   90.3  4.6820   4  307.0  21.0   
26    0.95577   0.0   8.14  0  0.538  6.047   88.8  4.4534   4  307.0  21.0   
27    0.77299   0.0   8.14  0  0.538  6.495   94.4  4.4547   4  307.0  21.0   
28    1.00245   0.0   8.14  0  0.538  6.674   87.3  4.2390   4  307.0  21.0   
29    1.13081   0.0   8.14  0  0.538  5.713   94.1  4.2330   4  307.0  21.0   
..        ...   ...    ... ..    ...    ...    ...     ...  ..    ...   ...   
475   4.87141   0.0  18.10  0  0.614  6.484   93.6  2.3053  24  666.0  20.2   
476  15.02340   0.0  18.10  0  0.614  5.304   97.3  2.1007  24  666.0  20.2   
477  10.23300   0.0  18.10  0  0.614  6.185   96.7  2.1705  24  666.0  20.2   
478  14.33370   0.0  18.10  0  0.614  6.229   88.0  1.9512  24  666.0  20.2   
479   5.82401   0.0  18.10  0  0.532  6.242   64.7  3.4242  24  666.0  20.2   
480   5.70818   0.0  18.10  0  0.532  6.750   74.9  3.3317  24  666.0  20.2   
481   5.73116   0.0  18.10  0  0.532  7.061   77.0  3.4106  24  666.0  20.2   
482   2.81838   0.0  18.10  0  0.532  5.762   40.3  4.0983  24  666.0  20.2   
483   2.37857   0.0  18.10  0  0.583  5.871   41.9  3.7240  24  666.0  20.2   
484   3.67367   0.0  18.10  0  0.583  6.312   51.9  3.9917  24  666.0  20.2   
485   5.69175   0.0  18.10  0  0.583  6.114   79.8  3.5459  24  666.0  20.2   
486   4.83567   0.0  18.10  0  0.583  5.905   53.2  3.1523  24  666.0  20.2   
487   0.15086   0.0  27.74  0  0.609  5.454   92.7  1.8209   4  711.0  20.1   
488   0.18337   0.0  27.74  0  0.609  5.414   98.3  1.7554   4  711.0  20.1   
489   0.20746   0.0  27.74  0  0.609  5.093   98.0  1.8226   4  711.0  20.1   
490   0.10574   0.0  27.74  0  0.609  5.983   98.8  1.8681   4  711.0  20.1   
491   0.11132   0.0  27.74  0  0.609  5.983   83.5  2.1099   4  711.0  20.1   
492   0.17331   0.0   9.69  0  0.585  5.707   54.0  2.3817   6  391.0  19.2   
493   0.27957   0.0   9.69  0  0.585  5.926   42.6  2.3817   6

In [67]:
df_data.as_matrix()

/Users/changmin.kim/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([[2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 3.9690e+02, 9.1400e+00,
        1.0000e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 3.9283e+02, 4.0300e+00,
        1.0000e+00],
       [3.2370e-02, 0.0000e+00, 2.1800e+00, ..., 3.9463e+02, 2.9400e+00,
        1.0000e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 5.6400e+00,
        1.0000e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 3.9345e+02, 6.4800e+00,
        1.0000e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 7.8800e+00,
        1.0000e+00]])

In [72]:
df_data.values

array([[2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 3.9690e+02, 9.1400e+00,
        1.0000e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 3.9283e+02, 4.0300e+00,
        1.0000e+00],
       [3.2370e-02, 0.0000e+00, 2.1800e+00, ..., 3.9463e+02, 2.9400e+00,
        1.0000e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 5.6400e+00,
        1.0000e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 3.9345e+02, 6.4800e+00,
        1.0000e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 7.8800e+00,
        1.0000e+00]])

In [73]:
df_data.values.T

array([[2.7310e-02, 2.7290e-02, 3.2370e-02, ..., 6.0760e-02, 1.0959e-01,
        4.7410e-02],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [7.0700e+00, 7.0700e+00, 2.1800e+00, ..., 1.1930e+01, 1.1930e+01,
        1.1930e+01],
       ...,
       [3.9690e+02, 3.9283e+02, 3.9463e+02, ..., 3.9690e+02, 3.9345e+02,
        3.9690e+02],
       [9.1400e+00, 4.0300e+00, 2.9400e+00, ..., 5.6400e+00, 6.4800e+00,
        7.8800e+00],
       [1.0000e+00, 1.0000e+00, 1.0000e+00, ..., 1.0000e+00, 1.0000e+00,
        1.0000e+00]])

In [98]:
m = df_data.values[1]

In [83]:
m.reshape(7,2)

array([[2.7290e-02, 0.0000e+00],
       [7.0700e+00, 0.0000e+00],
       [4.6900e-01, 7.1850e+00],
       [6.1100e+01, 4.9671e+00],
       [2.0000e+00, 2.4200e+02],
       [1.7800e+01, 3.9283e+02],
       [4.0300e+00, 1.0000e+00]])

In [87]:
h = m.reshape(2,1,7)
h

array([[[2.7290e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01,
         7.1850e+00, 6.1100e+01]],

       [[4.9671e+00, 2.0000e+00, 2.4200e+02, 1.7800e+01, 3.9283e+02,
         4.0300e+00, 1.0000e+00]]])

In [104]:
g = h.reshape(h.size,)

In [105]:
g.ndim

1

In [102]:
m.reshape(1,m.size)

array([[2.7290e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01,
        7.1850e+00, 6.1100e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02,
        1.7800e+01, 3.9283e+02, 4.0300e+00, 1.0000e+00]])

In [101]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [106]:
n = np.arange(1,10)

In [107]:
n

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
m=np.exp

In [109]:
m

<ufunc 'exp'>

In [14]:
test = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
test_1 = np.array([[1],[3],[5],[7]])

In [15]:
test

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [16]:
test_1

array([[1],
       [3],
       [5],
       [7]])

In [17]:
test + test_1

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [77]:
test_a = np.array([1,2,3],float)
test_b = np.array([11,12,13],float)

In [20]:
test_a < test_b

array([ True,  True,  True])

In [21]:
(test_a > test_b).any()

False

In [22]:
h = np.arange(2,10)

In [23]:
h

array([2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
y = np.arange(10)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
(test_a < 3).all() and (test_b>0).all()

False

In [38]:
np.where(test_a>2,"hello Man",7)

array(['7', '7', 'hello Man'], dtype='<U21')

In [45]:
u = np.array([1,None,5])

In [46]:
np.isnan(u)

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [48]:
c = np.array([[1,2,3,4],[5,6,7,8]])
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [49]:
np.argmax(c)

7

In [50]:
np.argmin(c)

0

In [52]:
np.argmax(c,axis=1)

array([3, 3])

In [54]:
(np.argmax(c), np.argmin(c))

(7, 0)

In [55]:
test_b>0

array([ True,  True,  True])

In [56]:
test_b>2

array([ True,  True,  True])

In [76]:
test_b

array([], shape=(0, 0, 0, 3), dtype=float64)

In [58]:
test_b>12

array([False, False,  True])

In [59]:
np.array(test_b>12)

array([False, False,  True])

In [60]:
test_b[test_b>12]

array([13.])

In [80]:
test_b
test_b[False]

array([], shape=(0, 3), dtype=float64)

array([], shape=(0, 0, 0, 3), dtype=float64)

In [82]:
test_a

array([1., 2., 3.])

In [83]:
bi = test_a < 2

In [84]:
bi.astype(np.int)

array([1, 0, 0])

In [94]:
Qi = np.array([2,4,6,8])
Bi = np.array([0,0,1,2,3,4],int)

In [95]:
Qi[Bi]

IndexError: index 4 is out of bounds for axis 0 with size 4

In [103]:
Qi[int(2),int(1)]

IndexError: too many indices for array

In [118]:
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [115]:
c[0,1] 

2

In [122]:
c[:3]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [127]:
list_data = [1,2,3,4,5]
example_obj = pd.Series(data=list_data)

In [128]:
example_obj

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [131]:
example_obj[1]

2

In [140]:
example = Series(data=(1,2,3,4,5,6),name="Hunter X Hunter",dtype=np.int32,index=("H","U","N","T","E","R"))

In [141]:
example

H    1
U    2
N    3
T    4
E    5
R    6
Name: Hunter X Hunter, dtype: int32

In [144]:
example["H"] = "가면라이더"

In [145]:
example

H    가면라이더
U        2
N        3
T        4
E        5
R        6
Name: Hunter X Hunter, dtype: object

In [146]:
example.values

array(['가면라이더', 2, 3, 4, 5, 6], dtype=object)

In [147]:
example.index

Index(['H', 'U', 'N', 'T', 'E', 'R'], dtype='object')

In [148]:
  example.index.name = "dragon"

In [149]:
example

dragon
H    가면라이더
U        2
N        3
T        4
E        5
R        6
Name: Hunter X Hunter, dtype: object

In [157]:
dict_data = {"a":1,"b":2,"c":3,"d":4,"e":5,"y":6}
dict_data

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'y': 6}

In [160]:
indexs = ["a","b","h","d","e","c","f"]
Series(data=dict_data,index=indexs,name="deceit")

a    1.0
b    2.0
h    NaN
d    4.0
e    5.0
c    3.0
f    NaN
Name: deceit, dtype: float64

In [236]:
datat = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]],dtype=np.float64)
indexss = ["H","U","N","T","E","R"]
columnss = [0,1,2]
data_frame = DataFrame(data=datat,index=indexss,columns=columnss)

data_frame

0     1     2
H   1.0   2.0   3.0
U   4.0   5.0   6.0
N   7.0   8.0   9.0
T  10.0  11.0  12.0
E  13.0  14.0  15.0
R  16.0  17.0  18.0

In [221]:
data_frame.0

SyntaxError: invalid syntax (<ipython-input-221-4e8e236bf52e>, line 1)

In [222]:
 data_frame[0]

1     1.0
2     4.0
3     7.0
4    10.0
5    13.0
6    16.0
Name: 0, dtype: float64

In [242]:
data_frame


0     1     2
H   1.0   2.0   3.0
U   4.0   5.0   6.0
N   7.0   8.0   9.0
T  10.0  11.0  12.0
E  13.0  14.0  15.0
R  16.0  17.0  18.0

In [244]:
data_frame.loc[:"N"]

0    1    2
H  1.0  2.0  3.0
U  4.0  5.0  6.0
N  7.0  8.0  9.0

In [240]:
data_frame.iloc[0]

0    1.0
1    2.0
2    3.0
Name: H, dtype: float64

In [287]:
n = data_frame[data_frame[1]>10]

In [288]:
n

0     1     2
T  10.0  11.0  12.0
E  13.0  14.0  15.0
R  16.0  17.0  18.0

In [301]:
n.values[:,1:3]

array([[11., 12.],
       [14., 15.],
       [17., 18.]])

In [302]:
n.values[:,1:3].T

array([[11., 14., 17.],
       [12., 15., 18.]])

In [303]:
del data_frame[2]

In [304]:
data_frame

0     1
H   1.0   2.0
U   4.0   5.0
N   7.0   8.0
T  10.0  11.0
E  13.0  14.0
R  16.0  17.0

In [2]:
source = {"name":["창민","진우","영준","인영","진표","주찬"],"age":[21,21,21,23,24,26],"habit":["프로그래밍","그림","카드","연애","인싸","더빙"]}

In [308]:
DataFrame(source)

{'name': ['창민', '진우', '영준', '인영', '진표', '주찬'],
 'age': [21, 21, 21, 23, 24, 26],
 'habit': ['프로그래밍', '그림', '카드', '연애', '인싸', '더빙']}

In [8]:
source1 = {"창민":{"age":21,"habit":"프로그래밍","성적":1},"진우":{"age":21,"habit":"그림","성적":3},"영준":{"age":20,"habit":"카드","성적":2}}
source1

{'창민': {'age': 21, 'habit': '프로그래밍', '성적': 1},
 '진우': {'age': 21, 'habit': '그림', '성적': 3},
 '영준': {'age': 20, 'habit': '카드', '성적': 2}}

In [9]:
source1

{'창민': {'age': 21, 'habit': '프로그래밍', '성적': 1},
 '진우': {'age': 21, 'habit': '그림', '성적': 3},
 '영준': {'age': 20, 'habit': '카드', '성적': 2}}

In [10]:
DataFrame(source1)

창민  진우  영준
age       21  21  20
habit  프로그래밍  그림  카드
성적         1   3   2

In [11]:
df = DataFrame(data=source1)

In [12]:
df

창민  진우  영준
age       21  21  20
habit  프로그래밍  그림  카드
성적         1   3   2

In [23]:
df.loc["age":].head(2).values

array([[21, 21, 20],
       ['프로그래밍', '그림', '카드']], dtype=object)

In [25]:
!conda install --y xlrd

Solving environment: done

## Package Plan ##

  environment location: /Users/changmin.kim/anaconda3

  added / updated specs:
    - xlrd


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.7.11               |           py37_0         2.8 MB
    ------------------------------------------------------------
                                           Total:         2.8 MB

The following packages will be UPDATED:

  conda                                       4.7.10-py37_0 --> 4.7.11-py37_0



conda-4.7.11         | 2.8 MB    | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done


In [26]:
df = pd.read_excel("./excel-comp-data.xlsx")

In [28]:
df.head(5)

account                         name                                street  \
0   211829   Kerluke, Koepp and Hilpert                    34456 Sean Highway   
1   320563               Walter-Trantow                     1311 Alvis Tunnel   
2   648336   Bashirian, Kunde and Price  62184 Schamberger Underpass Apt. 231   
3   109996  D'Amore, Gleichner and Bode           155 Fadel Crescent Apt. 144   
4   121213                Bauch-Goldner                   7274 Marissa Common   

              city          state  postal-code     Jan     Feb    Mar  
0       New Jaycob          Texas        28752   10000   62000  35000  
1    Port Khadijah  NorthCarolina        38365   95000   45000  35000  
2   New Lilianland           Iowa        76517   91000  120000  35000  
3       Hyattburgh          Maine        46021   45000  120000  10000  
4  Shanahanchester     California        49681  162000  120000  35000

In [31]:
df[["account","street","city"]]

account                                street               city
0    211829                    34456 Sean Highway         New Jaycob
1    320563                     1311 Alvis Tunnel      Port Khadijah
2    648336  62184 Schamberger Underpass Apt. 231     New Lilianland
3    109996           155 Fadel Crescent Apt. 144         Hyattburgh
4    121213                   7274 Marissa Common    Shanahanchester
5    132971                  89403 Casimer Spring       Jeremieburgh
6    145068          340 Consuela Bridge Apt. 400  Lake Gabriellaton
7    205217          91971 Cronin Vista Suite 601         Deronville
8    209744                      26739 Grant Lock    Lake Juliannton
9    212303             366 Maggio Grove Apt. 998          North Ras
10   214098             649 Cierra Forks Apt. 078           Rosaberg
11   231907              18115 Olivine Throughway      Norbertomouth
12   242368                       182 Bertie Road        East Davian
13   268755                  2624 Beatty Parkways       Goodwinmouth
14   273274                 8917 Bergstrom Meadow    Kathryneborough

In [34]:
df[:2]

account                        name              street           city  \
0   211829  Kerluke, Koepp and Hilpert  34456 Sean Highway     New Jaycob   
1   320563              Walter-Trantow   1311 Alvis Tunnel  Port Khadijah   

           state  postal-code    Jan    Feb    Mar  
0          Texas        28752  10000  62000  35000  
1  NorthCarolina        38365  95000  45000  35000

In [60]:
account_series = df[["account"]]

In [61]:
account_series

account
0    211829
1    320563
2    648336
3    109996
4    121213
5    132971
6    145068
7    205217
8    209744
9    212303
10   214098
11   231907
12   242368
13   268755
14   273274

In [65]:
account_series[:3]

account
0   211829
1   320563
2   648336

In [68]:
account_series<250000

account
0      True
1     False
2     False
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12     True
13    False
14    False

In [69]:
account_series[account_series<250000]

account
0   211829.0
1        NaN
2        NaN
3   109996.0
4   121213.0
5   132971.0
6   145068.0
7   205217.0
8   209744.0
9   212303.0
10  214098.0
11  231907.0
12  242368.0
13       NaN
14       NaN

In [70]:
df["account"]

0     211829
1     320563
2     648336
3     109996
4     121213
5     132971
6     145068
7     205217
8     209744
9     212303
10    214098
11    231907
12    242368
13    268755
14    273274
Name: account, dtype: int64

In [90]:
df.index = list(range(1,15))

ValueError: Length mismatch: Expected axis has 15 elements, new values have 14 elements

In [87]:
n

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [88]:
df

account                              name  \
0    211829        Kerluke, Koepp and Hilpert   
1    320563                    Walter-Trantow   
2    648336        Bashirian, Kunde and Price   
3    109996       D'Amore, Gleichner and Bode   
4    121213                     Bauch-Goldner   
5    132971  Williamson, Schumm and Hettinger   
6    145068                        Casper LLC   
7    205217                  Kovacek-Johnston   
8    209744                    Champlin-Morar   
9    212303                    Gerhold-Maggio   
10   214098       Goodwin, Homenick and Jerde   
11   231907                        Hahn-Moore   
12   242368      Frami, Anderson and Donnelly   
13   268755                       Walsh-Haley   
14   273274                     McDermott PLC   

                                  street               city          state  \
0                     34456 Sean Highway         New Jaycob          Texas   
1                      1311 Alvis Tunnel      Port Khadijah  NorthCarolina   
2   62184 Schamberger Underpass Apt. 231     New Lilianland           Iowa   
3            155 Fadel Crescent Apt. 144         Hyattburgh          Maine   
4                    7274 Marissa Common    Shanahanchester     California   
5                   89403 Casimer Spring       Jeremieburgh       Arkansas   
6           340 Consuela Bridge Apt. 400  Lake Gabriellaton     Mississipi   
7           91971 Cronin Vista Suite 601         Deronville    RhodeIsland   
8                       26739 Grant Lock    Lake Juliannton   Pennsylvania   
9              366 Maggio Grove Apt. 998          North Ras          Idaho   
10             649 Cierra Forks Apt. 078           Rosaberg       Tenessee   
11              18115 Olivine Throughway      Norbertomouth    NorthDakota   
12                       182 Bertie Road        East Davian           Iowa   
13                  2624 Beatty Parkways       Goodwinmouth    RhodeIsland   
14                 8917 Bergstrom Meadow    Kathryneborough       Delaware   

    postal-code     Jan     Feb     Mar  
0         28752   10000   62000   35000  
1         38365   95000   45000   35000  
2         76517   91000  120000   35000  
3         46021   45000  120000   10000  
4         49681  162000  120000   35000  
5         62785  150000  120000   35000  
6         18008   62000  120000   70000  
7         53461  145000   95000   35000  
8         64415   70000   95000   35000  
9         46308   70000  120000   35000  
10        47743   45000  120000   55000  
11        31415  150000   10000  162000  
12        72686  162000  120000   35000  
13        31919   55000  120000   35000  
14        27933  150000  120000   70000

In [91]:
df.drop([1,2,3])

account                              name                        street  \
0    211829        Kerluke, Koepp and Hilpert            34456 Sean Highway   
4    121213                     Bauch-Goldner           7274 Marissa Common   
5    132971  Williamson, Schumm and Hettinger          89403 Casimer Spring   
6    145068                        Casper LLC  340 Consuela Bridge Apt. 400   
7    205217                  Kovacek-Johnston  91971 Cronin Vista Suite 601   
8    209744                    Champlin-Morar              26739 Grant Lock   
9    212303                    Gerhold-Maggio     366 Maggio Grove Apt. 998   
10   214098       Goodwin, Homenick and Jerde     649 Cierra Forks Apt. 078   
11   231907                        Hahn-Moore      18115 Olivine Throughway   
12   242368      Frami, Anderson and Donnelly               182 Bertie Road   
13   268755                       Walsh-Haley          2624 Beatty Parkways   
14   273274                     McDermott PLC         8917 Bergstrom Meadow   

                 city         state  postal-code     Jan     Feb     Mar  
0          New Jaycob         Texas        28752   10000   62000   35000  
4     Shanahanchester    California        49681  162000  120000   35000  
5        Jeremieburgh      Arkansas        62785  150000  120000   35000  
6   Lake Gabriellaton    Mississipi        18008   62000  120000   70000  
7          Deronville   RhodeIsland        53461  145000   95000   35000  
8     Lake Juliannton  Pennsylvania        64415   70000   95000   35000  
9           North Ras         Idaho        46308   70000  120000   35000  
10           Rosaberg      Tenessee        47743   45000  120000   55000  
11      Norbertomouth   NorthDakota        31415  150000   10000  162000  
12        East Davian          Iowa        72686  162000  120000   35000  
13       Goodwinmouth   RhodeIsland        31919   55000  120000   35000  
14    Kathryneborough      Delaware        27933  150000  120000   70000

In [93]:
df.drop(index=[0,1],columns=["name","street"])

account               city         state  postal-code     Jan     Feb  \
2    648336     New Lilianland          Iowa        76517   91000  120000   
3    109996         Hyattburgh         Maine        46021   45000  120000   
4    121213    Shanahanchester    California        49681  162000  120000   
5    132971       Jeremieburgh      Arkansas        62785  150000  120000   
6    145068  Lake Gabriellaton    Mississipi        18008   62000  120000   
7    205217         Deronville   RhodeIsland        53461  145000   95000   
8    209744    Lake Juliannton  Pennsylvania        64415   70000   95000   
9    212303          North Ras         Idaho        46308   70000  120000   
10   214098           Rosaberg      Tenessee        47743   45000  120000   
11   231907      Norbertomouth   NorthDakota        31415  150000   10000   
12   242368        East Davian          Iowa        72686  162000  120000   
13   268755       Goodwinmouth   RhodeIsland        31919   55000  120000   
14   273274    Kathryneborough      Delaware        27933  150000  120000   

       Mar  
2    35000  
3    10000  
4    35000  
5    35000  
6    70000  
7    35000  
8    35000  
9    35000  
10   55000  
11  162000  
12   35000  
13   35000  
14   70000

In [38]:
df1 = pd.read_csv("./wages.csv")

In [45]:
df1.head(10)
y = (lambda n:0 if n=="male" else 1)
df1

earn  height     sex      race  ed  age  ses
0      79571.299011   73.89    male     white  16   49    0
1      96396.988643   66.23  female     white  16   62    1
2      48710.666947   63.77  female     white  16   33    1
3      80478.096153   63.22  female     other  16   95    1
4      82089.345498   63.08  female     white  17   43    1
5      15313.352901   64.53  female     white  15   30    1
6      47104.171821   61.54  female     white  12   53    1
7      50960.054282   73.29    male     white  17   50    0
8       3212.649556   72.24    male  hispanic  15   25    0
9      42996.637884   72.40    male     white  12   30    0
10     10328.618843   70.22    male     white  16   69    0
11      1002.307155   63.15  female     white  14   54    1
12     47597.819864   68.11    male     white  11   38    0
13     19019.542299   68.08    male     white  12   31    0
14     20063.996639   64.86  female     white  12   55    1
15       992.832346   60.06  female     white  12   31    1
16     35972.171123   66.01  female     white  16   39    1
17     26930.543964   68.07    male     white  12   62    0
18     64602.063972   68.16  female     white  14   33    1
19     69993.693070   70.02    male     white  13   48    0
20      1000.218306   67.08  female     white   9   25    1
21     12131.822115   64.20  female     black  12   59    1
22     84223.397919   72.76    male     black  13   39    0
23      8949.474935   62.17  female     white  13   55    1
24     23278.323278   63.04  female     white  14   25    1
25      8750.139185   66.67    male     white  14   26    0
26     64593.599805   65.95  female     white  12   45    1
27     54079.814945   71.69    male     white  12   49    0
28     16896.100044   62.76  female     black  12   39    1
29       -95.710279   68.46    male     white  11   25    0
...             ...     ...     ...       ...  ..  ...  ...
1349   64607.961872   65.68  female     white  16   63    1
1350   15899.403155   67.02    male     white  12   81    0
1351   25361.828379   66.10    male     white  12   41    0
1352   18482.957184   63.27  female     white   9   55    1
1353   26432.886457   67.89  female     white  13   47    1
1354   28644.500098   70.32    male     white  12   31    0
1355   20065.082736   62.98  female     white  16   30    1
1356    6354.842127   70.09    male     black  14   25    0
1357   95416.606798   71.92    male     white  12   49    0
1358   68428.923058   74.92    male     white  17   44    0
1359   50299.051292   61.97  female     white  14   43    1
1360   80518.409376   67.98  female     white  17   43    1
1361   43919.894343   68.18  female     white  14   33    1
1362   47712.440935   69.85    male     white  17   60    0
1363   19182.607431   73.26    male     black  13   25    0
1364     987.265131   69.01  female     white  16   43    1
1365   32798.051176   62.37  female     white  17   34    1
1366   24849.193294   60.30  female     black  12   80    1
1367   40757.935077   64.17  female     other  16   41    1
1368    4184.222685   60.19  female  hispanic   6   71    1
1369    4755.736508   72.94    male  hispanic  15   24    0
1370  175901.453598   65.90  female     other  18   52    1
1371   87473.968778   68.82    male     white  18   75    0
1372   92205.596106   69.62    male     white  18   57    0
1373   16905.557851   70.08  female     white  16   40    1
1374   30173.380363   71.68    male     white  12   33    0
1375   24853.519514   61.31  female     white  18   86    1
1376   13710.671312   63.64  female     white  12   37    1
1377   95426.014410   71.65    male     white  12   54    0
1378    9575.461857   68.22    male     white  12   31    0

[1379 rows x 7 columns]

In [41]:
df1["ses"] = df1["sex"].map(y)

In [42]:
df1

earn  height     sex      race  ed  age  ses
0      79571.299011   73.89    male     white  16   49    0
1      96396.988643   66.23  female     white  16   62    1
2      48710.666947   63.77  female     white  16   33    1
3      80478.096153   63.22  female     other  16   95    1
4      82089.345498   63.08  female     white  17   43    1
5      15313.352901   64.53  female     white  15   30    1
6      47104.171821   61.54  female     white  12   53    1
7      50960.054282   73.29    male     white  17   50    0
8       3212.649556   72.24    male  hispanic  15   25    0
9      42996.637884   72.40    male     white  12   30    0
10     10328.618843   70.22    male     white  16   69    0
11      1002.307155   63.15  female     white  14   54    1
12     47597.819864   68.11    male     white  11   38    0
13     19019.542299   68.08    male     white  12   31    0
14     20063.996639   64.86  female     white  12   55    1
15       992.832346   60.06  female     white  12   31    1
16     35972.171123   66.01  female     white  16   39    1
17     26930.543964   68.07    male     white  12   62    0
18     64602.063972   68.16  female     white  14   33    1
19     69993.693070   70.02    male     white  13   48    0
20      1000.218306   67.08  female     white   9   25    1
21     12131.822115   64.20  female     black  12   59    1
22     84223.397919   72.76    male     black  13   39    0
23      8949.474935   62.17  female     white  13   55    1
24     23278.323278   63.04  female     white  14   25    1
25      8750.139185   66.67    male     white  14   26    0
26     64593.599805   65.95  female     white  12   45    1
27     54079.814945   71.69    male     white  12   49    0
28     16896.100044   62.76  female     black  12   39    1
29       -95.710279   68.46    male     white  11   25    0
...             ...     ...     ...       ...  ..  ...  ...
1349   64607.961872   65.68  female     white  16   63    1
1350   15899.403155   67.02    male     white  12   81    0
1351   25361.828379   66.10    male     white  12   41    0
1352   18482.957184   63.27  female     white   9   55    1
1353   26432.886457   67.89  female     white  13   47    1
1354   28644.500098   70.32    male     white  12   31    0
1355   20065.082736   62.98  female     white  16   30    1
1356    6354.842127   70.09    male     black  14   25    0
1357   95416.606798   71.92    male     white  12   49    0
1358   68428.923058   74.92    male     white  17   44    0
1359   50299.051292   61.97  female     white  14   43    1
1360   80518.409376   67.98  female     white  17   43    1
1361   43919.894343   68.18  female     white  14   33    1
1362   47712.440935   69.85    male     white  17   60    0
1363   19182.607431   73.26    male     black  13   25    0
1364     987.265131   69.01  female     white  16   43    1
1365   32798.051176   62.37  female     white  17   34    1
1366   24849.193294   60.30  female     black  12   80    1
1367   40757.935077   64.17  female     other  16   41    1
1368    4184.222685   60.19  female  hispanic   6   71    1
1369    4755.736508   72.94    male  hispanic  15   24    0
1370  175901.453598   65.90  female     other  18   52    1
1371   87473.968778   68.82    male     white  18   75    0
1372   92205.596106   69.62    male     white  18   57    0
1373   16905.557851   70.08  female     white  16   40    1
1374   30173.380363   71.68    male     white  12   33    0
1375   24853.519514   61.31  female     white  18   86    1
1376   13710.671312   63.64  female     white  12   37    1
1377   95426.014410   71.65    male     white  12   54    0
1378    9575.461857   68.22    male     white  12   31    0

[1379 rows x 7 columns]

In [10]:
df1.race.unique()

array(['white', 'other', 'hispanic', 'black'], dtype=object)

In [49]:
df_info = df1[["earn", "height", "age"]]

In [50]:
df_info.head(10)

earn  height  age
0  79571.299011   73.89   49
1  96396.988643   66.23   62
2  48710.666947   63.77   33
3  80478.096153   63.22   95
4  82089.345498   63.08   43
5  15313.352901   64.53   30
6  47104.171821   61.54   53
7  50960.054282   73.29   50
8   3212.649556   72.24   25
9  42996.637884   72.40   30

In [52]:
f = lambda x: max(x) - min(x)
df_info.apply(f)

earn      318047.708444
height        19.870000
age           73.000000
dtype: float64

In [58]:
df_info.apply({lambda x:-x})

earn   height      age
           <lambda> <lambda> <lambda>
0     -79571.299011   -73.89      -49
1     -96396.988643   -66.23      -62
2     -48710.666947   -63.77      -33
3     -80478.096153   -63.22      -95
4     -82089.345498   -63.08      -43
5     -15313.352901   -64.53      -30
6     -47104.171821   -61.54      -53
7     -50960.054282   -73.29      -50
8      -3212.649556   -72.24      -25
9     -42996.637884   -72.40      -30
10    -10328.618843   -70.22      -69
11     -1002.307155   -63.15      -54
12    -47597.819864   -68.11      -38
13    -19019.542299   -68.08      -31
14    -20063.996639   -64.86      -55
15      -992.832346   -60.06      -31
16    -35972.171123   -66.01      -39
17    -26930.543964   -68.07      -62
18    -64602.063972   -68.16      -33
19    -69993.693070   -70.02      -48
20     -1000.218306   -67.08      -25
21    -12131.822115   -64.20      -59
22    -84223.397919   -72.76      -39
23     -8949.474935   -62.17      -55
24    -23278.323278   -63.04      -25
25     -8750.139185   -66.67      -26
26    -64593.599805   -65.95      -45
27    -54079.814945   -71.69      -49
28    -16896.100044   -62.76      -39
29        95.710279   -68.46      -25
...             ...      ...      ...
1349  -64607.961872   -65.68      -63
1350  -15899.403155   -67.02      -81
1351  -25361.828379   -66.10      -41
1352  -18482.957184   -63.27      -55
1353  -26432.886457   -67.89      -47
1354  -28644.500098   -70.32      -31
1355  -20065.082736   -62.98      -30
1356   -6354.842127   -70.09      -25
1357  -95416.606798   -71.92      -49
1358  -68428.923058   -74.92      -44
1359  -50299.051292   -61.97      -43
1360  -80518.409376   -67.98      -43
1361  -43919.894343   -68.18      -33
1362  -47712.440935   -69.85      -60
1363  -19182.607431   -73.26      -25
1364    -987.265131   -69.01      -43
1365  -32798.051176   -62.37      -34
1366  -24849.193294   -60.30      -80
1367  -40757.935077   -64.17      -41
1368   -4184.222685   -60.19      -71
1369   -4755.736508   -72.94      -24
1370 -175901.453598   -65.90      -52
1371  -87473.968778   -68.82      -75
1372  -92205.596106   -69.62      -57
1373  -16905.557851   -70.08      -40
1374  -30173.380363   -71.68      -33
1375  -24853.519514   -61.31      -86
1376  -13710.671312   -63.64      -37
1377  -95426.014410   -71.65      -54
1378   -9575.461857   -68.22      -31

[1379 rows x 3 columns]